-- 카페 리뷰 테이블
CREATE TABLE cafe_review ( rno INT NOT NULL AUTO_INCREMENT,
cno INT NOT NULL DEFAULT 0,
reviewtxt VARCHAR(1000) NOT NULL,
reviewer VARCHAR(50) NOT NULL,
regdate TIMESTAMP NOT NULL DEFAULT NOW(),
updatedate TIMESTAMP NOT NULL DEFAULT NOW(),
score INT NOT NULL DEFAULT 0,
PRIMARY KEY (rno)) DEFAULT CHARSET=utf8;

-- 리뷰 외래키 추가
ALTER TABLE cafe_review ADD CONSTRAINT FK_CAFE
FOREIGN KEY (cno) REFERENCES cafe_list (cno);